// <auto-generated />
namespace VendingMachine.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class For : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(For));
        
        string IMigrationMetadata.Id
        {
            get { return "201911221448315_For"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
